layout_spectrum: 0.3921665
typography_spectrum: 0.6344086
color:
  saturation: 0.4073475
  lightness: 0.8781362
  brandStrength: 0.1236559
  brandColors:
    - '#120E0D'
    - '#878A88'
    - '#A7311E'
    - '#A5781F'
    - '#CFA92E'
  rhythmicContrast: 0.8357251
name: Juwy Lim
